### PR TITLE
adding `isAggregator` flag

### PR DESCRIPTION
**Pull request by mbaudis**
This commit adds an optional `isAggregator` flag to `beaconResponseMeta` which will allow especially aggregators to avoid duplications & loops.

### CODE REVIEW

**Comment by mbaudis** [comment]
... and this is a non-breaking addition so no delay necessary.

**Comment by redmitry** [comment]
Would it be better to put it in the beaconInformationalResponseMeta?
I mean that if the endpoint is an aggregator all its beaconResponseMeta are also isAggregator?

Other thing is to distinguish resultsets, but in this case it should be per resultset (ResultsetInstance)?

Dmitry

**Comment by mbaudis** [comment]
@redmitry Good point; added it to `beaconInformationalResponseMeta`, too https://github.com/ga4gh-beacon/beacon-v2/pull/53/commits/4a6efe828a6d2bc70ea6999bfc5bc060fab753c3

But it should also stay in the normal responses since otherwise it could only be accessed w/ multiple passes.

Resultsets: The idea is that all resultSets are treated equally; i.e. an aggregator will concatenate the `ResultsetInstance` objects from different Beacons in its `resultSets`. With that we don't introduce another layer or type of response. However, it would be helpful here to have some dedicated source parameter which indicates the originating beacon.

**Comment by redmitry** [comment]
> it would be helpful here to have some dedicated source parameter which indicates the originating beacon.
Agree. Ideally it should contain the beacon identifier that originated the result set.
Something like "source": beaconId

**Comment by mbaudis** [comment]
@redmitry Like this https://github.com/ga4gh-beacon/beacon-v2/pull/53/commits/3f25a4501d6dad321927009acdbd32261b13457f ?

**Comment by redmitry** [comment]
> @redmitry Like this [3f25a45](https://github.com/ga4gh-beacon/beacon-v2/commit/3f25a4501d6dad321927009acdbd32261b13457f) ?

Yes. just.
>"Optional identifier of the beacon beacon this resultSet was collected from, especially for use in beacon aggregators."
"beacon beacon" :-)

**Pull request closed without merging**
