### PR TITLE
Framework refactor entry type definitions

### PR DESCRIPTION
**Pull request by mbaudis**
Some streamlining of the entryTypesDefinition schema. I think this is just a streamlining of the code which was a bit confusing but please check ...

### CODE REVIEW

**Review by costero-e — DISMISSED** [review]
Everything looks fine and is great to switch from http to https, as I see it is one of the main corrections along the files.

**Comment by costero-e** [comment]
For the branches management, this is the short-term plan:
**Deleted branches**
[genomicVariations_add-pathogenicity-predictions](https://github.com/ga4gh-beacon/beacon-v2/tree/genomicVariations_add-pathogenicity-predictions)
[clean-up_remove-validator-remnants](https://github.com/ga4gh-beacon/beacon-v2/tree/clean-up_remove-validator-remnants)
[clean-up_remove_aggregated_response](https://github.com/ga4gh-beacon/beacon-v2/tree/clean-up_remove_aggregated_response)

**Branches that will be deleted after PR #92**
[entry-type-definitions-cleanup](https://github.com/ga4gh-beacon/beacon-v2/tree/entry-type-definitions-cleanup)

**Branches that will be deleted after PR #90**
[hotfix_filteringTermsResults](https://github.com/ga4gh-beacon/beacon-v2/tree/hotfix_filteringTermsResults)

**Branches that will be deleted after PR #82**
[schema-urgent-fixes](https://github.com/ga4gh-beacon/beacon-v2/tree/schema-urgent-fixes)

**Branches that will be deleted after PR #74**
[clean-up_renaming_entity_to_entry_type](https://github.com/ga4gh-beacon/beacon-v2/tree/clean-up_renaming_entity_to_entry_type)

**Branches that will be deleted after this PR (#102)**
[framework-refactor-entry-type-definitions](https://github.com/ga4gh-beacon/beacon-v2/tree/framework-refactor-entry-type-definitions)

For the mid-term plan, I will write what we are doing in every branch and add milestones and achievements.

**Comment by jrambla** [comment]
Is this PR still mergeable?

**Comment by costero-e** [comment]
Hi @jrambla . Yes, it is mostly documentation and style updates apart from http to https changes. I think this won't break specifications. We need 1 pending review.

**Review by jrambla — APPROVED** [review]

**Comment by costero-e** [comment]
Closing this PR as some of this was already merged in other PR and conflicting files did not make it mergeable anymore.

**Pull request closed without merging**
