### PR TITLE
for templates the format must be "uri-template".

### PR DESCRIPTION
**Pull request by redmitry**
in the [beaconMapSchema.json](https://github.com/ga4gh-beacon/beacon-v2/blob/main/framework/json/configuration/beaconMapSchema.json) some URLs are templates and must have the uri-template" format (#103).

### CODE REVIEW

**Comment by jrambla** [comment]
IMU not all the uri you have modified are uri-templates (e.g. filteringterms).
I'm fine with changing all (?) to uri-templates, if a non-template uri could be expressed as uri-template, 
is that true?

**Comment by costero-e** [comment]
I would say uri-template is more like a type of uri, not the other way round. If we say something is a uri-template we are excluding uri that don't include braces {} with a parameter.
What do you think @redmitry ?

**Comment by redmitry** [comment]
https://datatracker.ietf.org/doc/html/rfc6570

uri-template is an URI "with variables" - it is as in the name - a template to produce the URI.
Technically any URI should be a valid template with no variables...
My point is that for the endpoints that includes {xxx} variables are not valid URIs, but are "uri-template"s.

Another thing is that Json Schemas 2019-2020 **by default** should just ignore "format". My validator validates it and reports an error. Current Beacon Network uses "fixed" schema (not from github) for  the /map:
see the difference: [beaconMapResponse.json](https://github.com/elixir-europe/neat-beacon-v2-validator/blob/master/beacon-v2-validator-code/src/main/resources/META-INF/schemas/beaconMapResponse.json
) vs [beaconEntryTypesResponse.json](https://github.com/elixir-europe/neat-beacon-v2-validator/blob/master/beacon-v2-validator-code/src/main/resources/META-INF/schemas/beaconEntryTypesResponse.json)

So could we use "uri-template" in all places? Yes. But I see no point. 

Best,

Dmitry

**Comment by costero-e** [comment]
Thank you @redmitry . So, are we still willing to accept this PR? Or can we close it?

**Comment by redmitry** [comment]
> Thank you @redmitry . So, are we still willing to accept this PR? Or can we close it?

IMO this should be in the main branch.

**Review by costero-e — APPROVED** [review]
If uri-template is a valid uri even if it doesn't carry variables within braces, this can be accepted from my side.

**Comment by costero-e** [comment]
Still, one review pending, @mbaudis or @jrambla. Thank you.

**Review by jrambla — APPROVED** [review]

**Pull request merged**
