### PR TITLE
complexValue required type fixed

### PR DESCRIPTION
**Pull request by costero-e**
This is the fix for the issue opened by @redmitry here #87 . Please @mbaudis and @redmitry review it to move this forward. Thank you.

### CODE REVIEW

**Review by redmitry — COMMENTED** [review]
... The "required" should by on the  "typedQuantities" property.

```json
"properties": {
        "typedQuantities": {
            "description": "List of quantities required to fully describe the complex value",
            "items": {
                "$ref": "#/definitions/TypedQuantity"
            },
            "type": "array"
        },
        "required": [ "typedQuantities" ]
    },
```
the removed part was ok:
```json
"required": [
                "quantityType",
                "quantity"
            ]
```

**Comment by costero-e** [comment]
Thank you @redmitry to spot that! I added another commit to fix the position of the required. Can you review it again and confirm it's correct now? Thanks.

**Comment by redmitry** [comment]
The last piece is to return back:

```json
            "required": [
                "quantityType",
                "quantity"
            ]
```
😄

**Comment by redmitry** [comment]
It looks correct now.
There is also an error in the the original CINECA Individuals data.
```json
"measurementValue" : {                                                                                                                                                                                          
    "quantity" : {                                                                                                                                                                                                  
        "unit" : {                                                                                                                                                                                                      
            "id" : "NCIT:C49671",                                                                                                                                                                                        
            "label" : "Kilogram per Square Meter"                                                                                                                                                                     
        },                                                                                                                                                                                                           
        "value" : 26.63838307                                                                                                                                                                                     
    }
}
```
while correct one  must be like:
```json
"measurementValue": {
    "unit": {
        "id": "NCIT:C49671",
        "label": "Kilogram per Square Meter"
    },
    "value": 26.63838307
}
```
I have a fixed version:
https://gitlab.bsc.es/inb/ga4gh/beacon-v2-docker-demo/-/tree/master/beacon-data

**Comment by mrueda** [comment]
Just a note, if we want to be Phenopacket friendly, I suggest changing our schema to align with theirs. When in trouble, I follow theirs...

See: https://phenopacket-schema.readthedocs.io/en/latest/value.html

and:

https://github.com/EGA-archive/beacon2-ri-tools/issues/3

Cheers,

m

**Review by mbaudis — APPROVED** [review]
Changes are good but there is an example (both yaml & json) which says "quentity"... I wonder who the original committer was ...

**Comment by mbaudis** [comment]
@mrueda 

> Just a note, if we want to be Phenopacket friendly, I suggest changing our schema to align with theirs. When in trouble, I follow theirs...

Tru dat. But PXF is inconsistent itself, at least when looking at the examples (and hampered by the "let's write this in YAML starting from a protobuf definition" documentation...):

[Value](https://phenopacket-schema.readthedocs.io/en/latest/value.html):

```
value:
    quantity:
        unit:
            id: "UO:0000316"
            label: "cells per microliter"
        value: 24000.0
        referenceRange:
            unit:
                id: "UO:0000316"
                label: "cells per microliter"
            low: 150000.0
            high: 450000.0
```

But example in [Measurement](https://phenopacket-schema.readthedocs.io/en/latest/measurement.html):

```
measurement:
    assay:
        id: "LOINC:26515-7"
        label: "Platelets [#/volume] in Blood"
    value:
        quantity:
            unit:
                id: "UO:0000316"
                label: "cells per microliter"
            value: 24000.0
    referenceRange:
        unit:
            id: "UO:0000316"
            label: "cells per microliter"
        low: 150000.0
        high: 450000.0
 ```

... places the `referenceRange` wrong.

**Review by redmitry — APPROVED** [review]
remember to validate individuals over fixed schema.

**Comment by costero-e** [comment]
yes @redmitry , I still have to take a look carefully at individuals issue before validating it.

**Comment by costero-e** [comment]
@redmitry I just checked the CINETICA individuals schema. Correct me if I'm wrong but I think the correction you made is because the value is not complex? Also, even if the value was complex, quantity should be an array not an object? 
@mrueda said that phenopackets (https://phenopacket-schema.readthedocs.io/en/latest/covid19-example.html) are written like this:
`measurements:
- assay:
    id: "NCIT:C113237"
    label: "Absolute Blood Lymphocyte Count"
  value:
    quantity:
      unit:
        id: "NCIT:C67245"
        label: "Thousand Cells"
      value: 1.4
      referenceRange:
        unit:
          id: "NCIT:C67245"
          label: "Thousand Cells"
        low: 1.0
        high: 4.5
  timeObserved:
    interval:
      start: "2019-09-01T00:00:00Z"
      end: "2020-03-01T00:00:00Z"
- assay:
    id: "NCIT:C113237"
    label: "Absolute Blood Lymphocyte Count"
  value:
    quantity:
      unit:
        id: "NCIT:C67245"
        label: "Thousand Cells"
      value: 0.7
      referenceRange:
        unit:
          id: "NCIT:C67245"
          label: "Thousand Cells"
        low: 1.0
        high: 4.5
  timeObserved:
    timestamp: "2020-03-20T00:00:00Z"`
Here I see the example value is not complex. 
I can correct the individuals schema but wouldn't be good for beacon to respect the phenopackets schema? I'm not saying I'm not going to do it, I just want to understand know why we are not following the same logic as for phenopackets schema. Thank you @redmitry !

**Comment by redmitry** [comment]
>can correct the individuals schema but wouldn't be good for beacon to respect the phenopackets schema?
IMHO phenopackets is not a schema, but a format that can be represented in json.

Beacon's schema != phenopackets. We may create an entry type "phenopackets" and provide a schema for it.

>Correct me if I'm wrong but I think the correction you made is because the value is not complex?
The correction to the CINECA data was done because it didn't comply with beacon v2 schema.

Cheers,

D.

**Comment by mrueda** [comment]
In my view, the difference between Beacon v2 and Phenopackets v2 schemas, specifically in the `individuals` entry type, likely stems from the reverse engineering of Phenopackets due to its Protobuff schema. If a JSON schema for Phenopackets v2 was available, this discrepancy wouldn't exist. As a developer working with BFF/PXF, these minor differences in defining identical terms/properties are impractical, especially since Beacon v2 was derived from Phenopackets and the goal is future interoperability.

The ideal scenario would be Phenopackets folks serializing their schema to JSON (if anybody from Phenopackets is reading this, please listen to us!! :smile:). However, if this isn't feasible, I propose forming a small working group of two/three people (@mbaudis) to identify and gradually address these differences. I would be eager to participate, given the impact on my work.

Cheers,

m

**Comment by mrueda** [comment]
@costero-e, IMO the key consideration here is whether the exclusion of the hierarchy 'quantity' from the Phenopacket schema was intentional or simply due to the challenges associated with reverse engineering the Protobuf schema. It should be noted that as of 2021, there were not many Phenopacket schemas available for 'Value'.

https://phenopacket-schema.readthedocs.io/en/master/value.html

If the downstream of the object 'Value' in Beacon v2 is identical to that in Phenopackets, it would be more reasonable to maintain consistency upstream as well. Instead of attempting to modify all replicas of CINECA's 'individuals.json', which is likely one of the few, if not the only, real examples that people have of Beacon v2 Models 😅 , it would be preferable to align the schema upstream and move on. What do you think @mbaudis?

Cheers,

Manu

**Comment by redmitry** [comment]
> Ok, then at the moment we will stick to specifications and give the CINECA dataset the schema suggested by @redmitry for measurementValues until we find a solution for the adaptability to Phenopackets.

The problem is that "phenopackets-schema" is not a JSON schema.
Phenopackets lib provides json serialization/deserialization, but not with defined (via schema) format.

The question is if it is feasible to develop "phenopackets-like" json schema, because in this case phenopackets would need to provide serializer/deserializer for it.

The choices are:

1. Leave it as is - Beacon uses it's own "phenopacket-like" format.
2. Beacon use phenopackes serialization format and would need to craft JSON schema that is in agreement with phenpackets format.
3. Develop complete JSON schema for phenopackets (incompatible with current phenopackets serialization).
3.1 use traditional JSON schema pattern with oneOf()
3.2 use VRS pattern where the type is explicitly set (e.g. "type": "Age") for each object

Cheers,

Dmitry

**Pull request merged**
