### PR TITLE
Fixed invalid syntax in `examples` #140

### PR DESCRIPTION
**Pull request by datsirul**
This PR addresses the invalid syntax in the `examples` parameter. It makes the model `endpoints` files valid OpenAPI documents.
For more info see issue #140.

### CODE REVIEW

**Review by jrambla — COMMENTED** [review]
I don't see any example with more than 1 value, as we had in the previous version.
Is that still possible with the "naming examples" approach?

**Comment by mbaudis** [comment]
... and maybe using descriptive names? I'm 60/40 on this `¯\_(ツ)_/¯`

**Comment by datsirul** [comment]
Sure, I think naming the examples would be the better approach and even provide better experiences in response mocking scenarios.
What would be the best approach to name these? Can anyone provide names, or is there a good way for me to look up these values?

**Comment by jrambla** [comment]
@datsirul are you waiting for feedback on your last comment, right?

**Comment by jrambla** [comment]
@datsirul ??

**Pull request merged**
