### PR TITLE
Removing unused filteringTerms.yaml & json files

### PR DESCRIPTION
**Pull request by jrambla**
This PR is to remove the unused filteringTerms files, according to issues #159 , #93

### CODE REVIEW

**Review by redmitry — APPROVED** [review]

**Review by mbaudis — APPROVED** [review]

**Comment by mbaudis** [comment]
@jrambla @costero-e Just a note: This PR is against `main` which IMO doesn't is a problem _per se_ but don't we do some staging at `develop` & update in bulk?

**Comment by costero-e** [comment]
@mbaudis yes, absolutely, if this is not an urgent fix, in which case it can go directly to main, then it should go to develop for later addition to main (when version change is updated). @jrambla, could we merge this into develop and then include it in 2.2.0 milestone for further merging to main?

**Comment by jrambla** [comment]
IMHO, we (should?) have four main branches: main, develop, fixes & cleanup... 
I don't know if this is clear in the 'branch management' discussion or indeed my opinion contradicts it. Does it?
I didn't make the PR against clean-up because it seemed to me that these branches are having issues. If not, that would be my preferred place for this PR.
Makes sense?

**Comment by mbaudis** [comment]
> IMHO, we (should?) have four main branches: main, develop, fixes & cleanup... 

Well, we should have one to drop things in which have been reviewed and which is always updated from main, and then do minor version updates with some collected changes. Otherwise it becomes a bit messy if you want to track back... But I'm certainly fine with doing "collective merge + version bump" sessions :-)

**Comment by jrambla** [comment]
In my view: all/most branches should have reviews, all of them should merge into main and all changes should be assigned to a version. 
Are we saying the same, @mbaudis  ?

**Comment by costero-e** [comment]
> IMHO, we (should?) have four main branches: main, develop, fixes & cleanup... I don't know if this is clear in the 'branch management' discussion or indeed my opinion contradicts it. Does it? I didn't make the PR against clean-up because it seemed to me that these branches are having issues. If not, that would be my preferred place for this PR. Makes sense?

Hi @jrambla, yes, it makes sense to have these branches with a cleanup branch. Let me update the cleanup branch to make these cleanups mergeable.

**Comment by costero-e** [comment]
Done, please, @jrambla and @mbaudis, tell me if we are good now to submit the Pull Request. 😄

**Comment by mbaudis** [comment]
Merging into clean-up.

**Pull request merged**
