### PR TITLE
missing object type fix

### PR DESCRIPTION
**Pull request by mbaudis**
`ResultsetInstance` was missing the "type" parameter which leads to errors when creating instances.

Tis is an urgent fix w/o any changes to the schema etc. and IMO should directly go into `main` instead of `develop` etc.

### CODE REVIEW

**Comment by costero-e** [comment]
Yes, this can be considered a hotfix so I agree this is one of the case scenarios in which a PR directly to main is appropriate.

**Review by costero-e — APPROVED** [review]

**Comment by jrambla** [comment]
I miss an update to Change.MD in order to notify the change.
However, I'm a little confused that it is not working as it is now (w/o the "type" attribute), as we have tested throught schema validators.
Just tested again with a mock schema and document. Removing "type: object" doesn't raises any complaint from the validator.

**Comment by mbaudis** [comment]
@jrambla The missing `object` type can lead to schema parsers failing to transverse the schema structure. In my testing failed to instantiate an object from the schema. But anyway - should be there as everywhere else.

**Comment by costero-e** [comment]
we need @jrambla approval here to close this PR

**Comment by jrambla** [comment]
This PR requires a review from the current status

**Comment by costero-e** [comment]
These are fixes that won't break the specification, just addressing examples for ageOfOnset, which were including the entry definitions (and the schema don't need to add this information), as well as adding object type for ResultSetInstance (and other format fixes). Still 1 pending review.

**Review by jrambla — APPROVED** [review]

**Pull request merged**
